### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by gdzqzzx** [BarraQDA/nvivotools#11]
I'm using sqlAlchemy 1.4.7 and got following import error when running ```python DenormaliseDB.py``` and ```python NormaliseDB.py``` (test only, no input parameters):

```
  File "NormaliseDB.py", line 20, in <module>
    import NVivo
  File "...\nvivotools-master\NVivo.py", line 48, in <module>
    exec(open(os.path.dirname(os.path.realpath(__file__)) + os.path.sep + 'DataTypes.py').read())
  File "<string>", line 27, in <module>
ImportError: cannot import name 'Binary' from 'sqlalchemy' (...\sqlalchemy\__init__.py)
```

```
Traceback (most recent call last):
  File "DenormaliseDB.py", line 20, in <module>
    import NVivo
  File "...\nvivotools-master\NVivo.py", line 48, in <module>
    exec(open(os.path.dirname(os.path.realpath(__file__)) + os.path.sep + 'DataTypes.py').read())
  File "<string>", line 27, in <module>
ImportError: cannot import name 'Binary' from 'sqlalchemy' (...\sqlalchemy\__init__.py)
```

It seems that somehow the query returned ```bytes``` as mentioned [here](https://stackoverflow.com/questions/61161498/why-binary-usage-in-sqlalchemy-with-python3-cause-a-typeerror-string-argument).

**Comment by jschultz** [comment]
The problem seems to be that since version 1.4 SQLAlchemy has changed the type name from `Binary` to `BINARY`. I've pushed a commit that should fix it.

By the way it was my mistake to say you should run `DenormaliseNVP.py` - if you want to convert from NVivo to another format you should run `NormaliseNVP.py`. `NormaliseDB.py` should also work if you have already attached the database but it is simpler to use `NormaliseNVP.py` which will do the whole procedure. Plus I would like to get to the bottom of the issue you have encountered where the mounting process didn't work.

**Comment by gdzqzzx** [comment]
Thank you so much for the quick response!

I will test it again after your new comitting. Since my team is not going to use NVivo on next stage, I have more time to play with NVivotools and help to improve it now.

I have reopened [#10](https://github.com/BarraQDA/nvivotools/issues/10), please let me know if you have further information you want to know there.

**Comment by gdzqzzx** [comment]
> The problem seems to be that since version 1.4 SQLAlchemy has changed the type name from `Binary` to `BINARY`. I've pushed a commit that should fix it.
> 
> By the way it was my mistake to say you should run `DenormaliseNVP.py` - if you want to convert from NVivo to another format you should run `NormaliseNVP.py`. `NormaliseDB.py` should also work if you have already attached the database but it is simpler to use `NormaliseNVP.py` which will do the whole procedure. Plus I would like to get to the bottom of the issue you have encountered where the mounting process didn't work.

Import Error in 1.4 SQLAlchemy is fixed
